City.create(name: 'Biała Podlaska', short_name: 'BP')
City.create(name: 'Biłgoraj', short_name: 'BI')
City.create(name: 'Chełm', short_name: 'CH')
City.create(name: 'Hrubieszów', short_name: 'HR')
City.create(name: 'Janów Lubelski', short_name: 'JL')
City.create(name: 'Krasnystaw', short_name: 'KY')
City.create(name: 'Kraśnik', short_name: 'KK')
City.create(name: 'Lubartów', short_name: 'LT')
City.create(name: 'Lublin', short_name: 'LB')
City.create(name: 'Łęczna', short_name: 'LC')
City.create(name: 'Łuków', short_name: 'LW')
City.create(name: 'Opole Lubelskie', short_name: 'OB')
City.create(name: 'Parczew', short_name: 'PC')
City.create(name: 'Puławy', short_name: 'PU')
City.create(name: 'Radzyń Podlaski', short_name: 'RP')
City.create(name: 'Ryki', short_name: 'RK')
City.create(name: 'Świdnik', short_name: 'SD')
City.create(name: 'Tomaszów Lubelski', short_name: 'TL')
City.create(name: 'Włodawa', short_name: 'WD')
City.create(name: 'Zamość', short_name: 'ZA')
City.create(name: 'Bolesławiec', short_name: 'BE')
City.create(name: 'Dzierżoniów', short_name: 'DZ')
City.create(name: 'Głogów', short_name: 'GG')
City.create(name: 'Góra', short_name: 'GX')
City.create(name: 'Jawor', short_name: 'JR')
City.create(name: 'Jelenia Góra', short_name: 'JG')
City.create(name: 'Kamienna G.', short_name: 'KQ')
City.create(name: 'Kłodzko', short_name: 'KV')
City.create(name: 'Legnica', short_name: 'LG')
City.create(name: 'Lubań', short_name: 'LH')
City.create(name: 'Lubin', short_name: 'UN')
City.create(name: 'Lwówek Śl.', short_name: 'LF')
City.create(name: 'Milicz', short_name: 'ML')
City.create(name: 'Oleśnica', short_name: 'OE')
City.create(name: 'Oława', short_name: 'OA')
City.create(name: 'Polkowice', short_name: 'PP')
City.create(name: 'Strzelin', short_name: 'SV')
City.create(name: 'Środa Śl.', short_name: 'SS')
City.create(name: 'Świdnica', short_name: 'ID')
City.create(name: 'Trzebnica', short_name: 'TR')
City.create(name: 'Wałbrzych', short_name: 'WB')
City.create(name: 'Wołów', short_name: 'WQ')
City.create(name: 'Wrocław', short_name: 'WR')
City.create(name: 'Ząbkowice', short_name: 'ZS')
City.create(name: 'Zgorzelec', short_name: 'ZO')
City.create(name: 'Złotoryja', short_name: 'ZT')

user = CreateAdminService.new.call
puts 'CREATED ADMIN USER: ' << user.email
